name: Node Support Request
description: Request support for an unsupported ComfyUI node
title: 'Node Support Request: '
labels: ['node-support', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request node support!

        ![Export Workflow](https://github.com/ShunL12324/comfy-portal/raw/workflow-exp/repo-assets/issue-template/export-workflow.png)

        To help us better understand your request, please provide your workflow JSON file:
        1. Open ComfyUI in your web browser
        2. Go to Menu > Workflow > Export
        3. Save the workflow JSON file
        4. ⚠️ Please remove any sensitive information from the JSON file before sharing
        5. You can either:
           - Drag and drop the JSON file directly into this issue
           - Or upload it to [Pastebin](https://pastebin.com) / [GitHub Gist](https://gist.github.com) and share the link

        > ℹ️ Without the workflow JSON file, we won't be able to add support for the node.

  - type: input
    id: node-type
    attributes:
      label: Node Type
      description: The type/class name of the node
      placeholder: 'Example: KSampler'
    validations:
      required: false

  - type: input
    id: workflow-link
    attributes:
      label: Workflow JSON Link (Optional)
      description: If you prefer, you can share a link to your workflow JSON file
      placeholder: 'https://pastebin.com/... or drag & drop the file directly into the issue'
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context or information about this node
      placeholder: 'Example: This node is part of the...'
    validations:
      required: false
