title: Comfy Portal Documentation
description: Documentation and guides for Comfy Portal
baseurl: ''
url: 'https://shunl12324.github.io/comfy-portal'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  content:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: '_content/guide'
    values:
      layout: guide
