title: Comfy Portal Documentation
description: Documentation for Comfy Portal - Your AI Image Generation Assistant

# Site settings
baseurl: '/comfy-portal' # GitHub Pages repository name
url: 'https://shunl12324.github.io' # GitHub Pages URL

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: text
    guess_lang: true

# Collections
collections:
  guide:
    output: true
    permalink: /guide/:path/

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: 'guide'
      type: 'guide'
    values:
      layout: guide

# Exclude from processing
exclude:
  - 'node_modules'
  - 'vendor/*'
  - 'Gemfile'
  - 'Gemfile.lock'
  - .sass-cache/
  - .jekyll-cache/

sass:
  sass_dir: assets/css # 指向现有CSS目录
