source "https://rubygems.org"

# Standard libraries that will be removed from default gems
gem "csv"
gem "base64"
gem "logger"

gem "jekyll", "~> 4.3.3"
gem "webrick", "~> 1.8"
gem "jekyll-sass-converter"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end
